name: blog
description: "dev-hann's blog"
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  flex_color_scheme: ^7.3.1
  flutter_svg: ^2.0.10+1
  equatable:
  flutter_markdown: ^0.7.3
  markdown:
  dio:
  riverpod:
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  freezed:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.2
  build_runner: ^2.4.12
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
