name: blog
description: "dev-hann's blog"
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  flex_color_scheme: ^7.3.1
  flutter_svg: ^2.0.10+1
  equatable:
  flutter_markdown: ^0.7.3
  markdown:
  dio:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
